{
  service: "sign-bot",
  frameworkVersion: "3",

  package: {
    excludeDevDependencies: true,
  },

  provider: {
    name: "aws",
    runtime: "nodejs16.x",
    region: "eu-west-1"
  },

  plugins: [
    "serverless-plugin-typescript"
  ],

  functions: {
    signBot: {
      name: "sign-bot",
      handler: "handler.botHandler",
      events: [
        {
          httpApi: {
            path: "/telegraf",
            method: "post",
          },
        },
      ],
    },
  },
}